[profile.default]
  libs = ['lib']
  optimizer_runs = 1_000_000
  out = 'out'
  src = 'src'
  # the following setting ensures that deterministically deployed contracts will always be to the same address
  auto_detect_solc = false
  bytecode_hash = "none"
  gas_reports = []
  remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "hats-module/=lib/hats-module/src/",
    "solady/=lib/hats-module/lib/solady/src/",
  ]
  solc = "0.8.19"
  # Enable tests to read ir-optimized bytecode precompiled by profile.optimized
  fs_permissions = [{ access = "read", path = "./optimized-out" }]

# for pre-compiling ir-optimized bytecode that will be later deployed by tests
[profile.optimized]
  bytecode_hash = "none"
  out = "optimized-out"
  script = "src"
  sizes = true
  via_ir = true
  # no need to compile tests with via-ir since they load optimized bytecode directly by default
  test = "src"

# for running tests against pre-compiled ir-optimized deployments
[profile.test]
  src = "test"

[profile.ci]
  fuzz = { runs = 5000 }
  invariant = { runs = 1000 }

[profile.lite]
  fuzz = { runs = 32 }
  invariant = { runs = 10 }
  # Speed up compilation and tests during development.
  optimizer = false

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 2
  wrap_comments = true

[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"
  gnosis = "${GC_RPC}"
  goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
  local = "http://localhost:8545"
  mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
  optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"
  polygon = "${POLYGON_RPC}"
  sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"

[etherscan]
  arbitrum = { key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api" }
  gnosis = { key = "${GNOSISSCAN_KEY}", url = "https://api.gnosisscan.io/api" }
  goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
  mainnet = { key = "${ETHERSCAN_KEY}", url = "https://api.etherscan.io/api" }
  optimism = { key = "${OPTIMISM_KEY}", url = "https://api-optimistic.etherscan.io/api" }
  polygon = { key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api" }
  sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api" }

  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
